package gitlab

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

func newTestClient(server *httptest.Server) *httpClient {
	return &httpClient{
		http:    server.Client(),
		baseURL: server.URL,
		token:   "test-token",
		backoff: 1 * time.Millisecond,
		retries: 3,
	}
}

func standardCommitRequest() CommitRequest {
	return CommitRequest{
		ProjectID:        "kineticz/pipelines",
		SourceBranch:     "kineticz/tok-abc",
		TargetBranch:     "main",
		FilePath:         "internal/pipeline/users.go",
		FileContent:      []byte("package pipeline\n// patched\n"),
		CommitMessage:    "Apply Kineticz patch",
		CorrelationToken: "tok-abc",
	}
}

func standardMRRequest() MRRequest {
	return MRRequest{
		ProjectID:        "kineticz/pipelines",
		SourceBranch:     "kineticz/tok-abc",
		TargetBranch:     "main",
		Title:            "Auto-patch users_v1",
		Description:      "Generated by Kineticz.",
		CorrelationToken: "tok-abc",
	}
}

func TestCreateCommit_HappyPath(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("PRIVATE-TOKEN") != "test-token" {
			http.Error(w, "missing token", http.StatusUnauthorized)
			return
		}
		if r.Header.Get("X-Correlation-Token") != "tok-abc" {
			http.Error(w, "missing correlation header", http.StatusBadRequest)
			return
		}
		if !strings.Contains(r.URL.Path, "/repository/commits") {
			http.Error(w, "wrong path", http.StatusNotFound)
			return
		}
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "decode", http.StatusBadRequest)
			return
		}
		actions, _ := body["actions"].([]any)
		if len(actions) != 1 {
			http.Error(w, "expected 1 action", http.StatusBadRequest)
			return
		}
		w.WriteHeader(http.StatusCreated)
		_, _ = w.Write([]byte(`{"id":"abc123def456"}`))
	}))
	defer server.Close()
	c := newTestClient(server)

	sha, err := c.CreateCommit(context.Background(), standardCommitRequest())
	if err != nil {
		t.Fatalf("CreateCommit: %v", err)
	}
	if sha != "abc123def456" {
		t.Errorf("sha = %q, want abc123def456", sha)
	}
}

func TestCreateCommit_MergeConflictReturnsErrMergeConflict(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusConflict)
		_, _ = w.Write([]byte(`{"message":"branch already exists"}`))
	}))
	defer server.Close()
	c := newTestClient(server)
	_, err := c.CreateCommit(context.Background(), standardCommitRequest())
	if !errors.Is(err, ErrMergeConflict) {
		t.Fatalf("err = %v, want ErrMergeConflict", err)
	}
}

func TestCreateMR_PrependsCorrelationTokenAndPathHasMR(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.Contains(r.URL.Path, "/merge_requests") {
			http.Error(w, "wrong path", http.StatusNotFound)
			return
		}
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "decode", http.StatusBadRequest)
			return
		}
		desc, _ := body["description"].(string)
		if !strings.HasPrefix(desc, "X-Correlation-Token: tok-abc") {
			http.Error(w, "description missing correlation prefix", http.StatusBadRequest)
			return
		}
		w.WriteHeader(http.StatusCreated)
		_, _ = w.Write([]byte(`{"iid":42,"web_url":"https://gitlab.example/mr/42"}`))
	}))
	defer server.Close()
	c := newTestClient(server)
	mr, err := c.CreateMR(context.Background(), standardMRRequest())
	if err != nil {
		t.Fatalf("CreateMR: %v", err)
	}
	if mr.MRIID != 42 {
		t.Errorf("MRIID = %d, want 42", mr.MRIID)
	}
	if mr.MRURL != "https://gitlab.example/mr/42" {
		t.Errorf("MRURL = %q", mr.MRURL)
	}
}

func TestGitLabClient_5xxExhaustsRetries(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusServiceUnavailable)
		_, _ = w.Write([]byte(`{"error":"upstream"}`))
	}))
	defer server.Close()
	c := newTestClient(server)
	_, err := c.CreateCommit(context.Background(), standardCommitRequest())
	if !errors.Is(err, ErrGitLabUnavailable) {
		t.Fatalf("err = %v, want ErrGitLabUnavailable", err)
	}
}

func TestGitLabClient_4xxReturnsGitLabError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusUnprocessableEntity)
		_, _ = w.Write([]byte(`{"error":"validation failed"}`))
	}))
	defer server.Close()
	c := newTestClient(server)
	_, err := c.CreateMR(context.Background(), standardMRRequest())
	if err == nil {
		t.Fatal("expected error")
	}
	var gerr *GitLabError
	if !errors.As(err, &gerr) {
		t.Errorf("err = %v, want *GitLabError", err)
	}
}
